# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainW.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainW(object):
    def setupUi(self, MainW):
        MainW.setObjectName("MainW")
        MainW.resize(1077, 600)
        font = QtGui.QFont()
        font.setPointSize(20)
        MainW.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainW)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(590, 20, 20, 571))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(650, 80, 411, 161))
        self.treeWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(770, 370, 211, 51))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(790, 430, 181, 71))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 60, 211, 41))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 70, 181, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 120, 181, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 110, 171, 51))
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(100, 170, 51, 41))
        self.spinBox.setObjectName("spinBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 170, 291, 41))
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(70, 240, 151, 31))
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(70, 280, 141, 31))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 440, 281, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        MainW.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainW)
        QtCore.QMetaObject.connectSlotsByName(MainW)

    def retranslateUi(self, MainW):
        _translate = QtCore.QCoreApplication.translate
        MainW.setWindowTitle(_translate("MainW", "PAP"))
        self.treeWidget.headerItem().setText(0, _translate("MainW", "1"))
        self.treeWidget.headerItem().setText(1, _translate("MainW", "New Column"))
        self.treeWidget.headerItem().setText(2, _translate("MainW", "New Column"))
        self.treeWidget.headerItem().setText(3, _translate("MainW", "New Column"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainW", "New Item"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainW", "New Item"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainW", "New Item"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainW", "New Item"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.commandLinkButton.setText(_translate("MainW", "Открыть для просмотра"))
        self.pushButton.setText(_translate("MainW", "Удалить"))
        self.label.setText(_translate("MainW", "Наименование"))
        self.label_2.setText(_translate("MainW", "Комментарий"))
        self.label_3.setText(_translate("MainW", "КОличество элементов"))
        self.checkBox.setText(_translate("MainW", "TO1"))
        self.checkBox_2.setText(_translate("MainW", "TO2"))
        self.pushButton_2.setText(_translate("MainW", "Создать"))
